

namespace Gui
{
    using System.Diagnostics.CodeAnalysis;
    using System.Windows.Forms;

    using CustomEvents;

    using GuiController;

    /// <summary>
    /// The main form for the application
    /// </summary>
    public partial class MainForm : Form
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MainForm"/> class.
        /// </summary>
        public MainForm()
        {
            this.InitializeComponent();
            this.InitEventListeners();
        }

        private void InitEventListeners()
        {
            UpdateGui.UpdateStockEvent += this.UpdateStockPredictions;
        }

        private void UpdateStockPredictions(string stockPrediction)
        {
            this.richTextBoxPredictions.Text = stockPrediction;
        }

        /// <summary>
        /// Hooks onto buttonPredict click event
        /// </summary>
        /// <param name="sender">The context</param>
        /// <param name="e">event arguments</param>
        [SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:ElementMustBeginWithUpperCaseLetter", Justification = "Auto-generated by IDE")]
        private void buttonPredict_Click(object sender, System.EventArgs e)
        {
            var controller = new MakePredictions(this.textBoxEnterTicker.Text, this.comboBoxInfoSource.Text);
        }
    }
}
