

namespace Gui
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    using System.Threading.Tasks;
    using System.Windows.Forms;

    using GuiController;

    using MessageBroker;

    /// <summary>
    /// The main form for the application
    /// </summary>
    public partial class MainForm : Form
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MainForm"/> class.
        /// </summary>
        public MainForm()
        {
            this.InitializeComponent();
            this.InitEventListeners();
            this.StartConsumer();
        }

        /// <summary>
        /// Starts subscriber for predictions
        /// </summary>
        private void StartConsumer()
        {
            const string HostName = "localhost";
            const string Queue = "resp_stock";
            var consumer = new Consumer(HostName, Queue);
            consumer.Initialize();
            Task.Run(() => consumer.Consume());
        }

        /// <summary>
        /// Initializes the events to run methods when triggered.
        /// </summary>
        private void InitEventListeners()
        {
            CustomEvents.UpdateGui.UpdateStockEvent += this.UpdateGui;
            CustomEvents.CustomDisplayError.DisplayErrorEvent += this.ShowErrorMessage;
        }

        /// <summary>
        /// Updates GUI with new predictions.
        /// </summary>
        /// <param name="message">the returned message from backend.</param>
        private void UpdateGui(string message)
        {
            var stockMessage = JsonHandler.DeserializeStockMessage(message);
            this.UpdateStockPredictions(stockMessage.ModelConfidence);
            this.UpdateGraph(stockMessage.GraphLocation);
        }

        /// <summary>
        /// Displays an error message in a message box.
        /// </summary>
        /// <param name="errorMessage">The message to display, it is stored in the model confidence param</param>
        private void ShowErrorMessage(string errorMessage)
        {
            var stockMessage = JsonHandler.DeserializeStockMessage(errorMessage);
            MessageBox.Show(stockMessage.ModelConfidence, "Error");
        }

        /// <summary>
        /// Updates the GUI to display predictions
        /// </summary>
        /// <param name="confidenceOfModel">the confidence of the model used.</param>
        private void UpdateStockPredictions(string confidenceOfModel)
        {
            if (this.richTextBoxPredictions.InvokeRequired)
            {
                this.richTextBoxPredictions.Invoke((MethodInvoker)delegate
                {
                    var timeOfMessage = DateTime.Now.ToString("HH:mm:ss.fff");
                    this.richTextBoxPredictions.AppendText($"\nReceived at: {timeOfMessage}\n{confidenceOfModel}");
                });
            }
            else
            {
                this.richTextBoxPredictions.Text += DateTime.Now.ToString("mm:ss.fff");
                var timeOfMessage = DateTime.Now.ToString("HH:mm:ss.fff");
                this.richTextBoxPredictions.AppendText($"\nReceived at: {timeOfMessage}\n{confidenceOfModel}");
            }
        }

        /// <summary>
        /// updates the picture box with generated graph of predictions
        /// </summary>
        /// <param name="location">the file path of the graph</param>
        private void UpdateGraph(string location)
        {
            if (this.pictureBoxGraph.InvokeRequired)
            {
                this.pictureBoxGraph.ImageLocation = location;
                this.pictureBoxGraph.SizeMode = PictureBoxSizeMode.StretchImage;
            }
            else
            {
                this.pictureBoxGraph.ImageLocation = location;
                this.pictureBoxGraph.SizeMode = PictureBoxSizeMode.StretchImage;
            }
        }

        /// <summary>
        /// Hooks onto buttonPredict click event
        /// </summary>
        /// <param name="sender">The context</param>
        /// <param name="e">event arguments</param>
        [SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:ElementMustBeginWithUpperCaseLetter", Justification = "Auto-generated by IDE")]
        private void buttonPredict_Click(object sender, EventArgs e)
        {
            var ticker = this.textBoxEnterTicker.Text;
            if (ticker == "")
            {
                MessageBox.Show("Please enter a Ticker in the box, example: AAPL", "Error");
                return;
            }

            var source = this.comboBoxInfoSource.Text;
            if (source == "")
            {
                MessageBox.Show("Please select an information source.", "Error");
                return;
            }

            var modelType = this.comboBoxModelType.Text;
            if (source == "")
            {
                MessageBox.Show("Please select a model to use.", "Error");
                return;
            }

            var controller = new MakePredictions(ticker, source, modelType);
            controller.GetPredictions();
        }
    }
}
