

namespace Gui
{
    using System.Diagnostics.CodeAnalysis;
    using System.Threading.Tasks;
    using System.Windows.Forms;

    using CustomEvents;

    using GuiController;

    using MessageBroker;

    /// <summary>
    /// The main form for the application
    /// </summary>
    public partial class MainForm : Form
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MainForm"/> class.
        /// </summary>
        public MainForm()
        {
            this.InitializeComponent();
            this.InitEventListeners();
            this.StartConsumer();
        }

        /// <summary>
        /// Starts subscriber for predictions
        /// </summary>
        private void StartConsumer()
        {
            var consumer = new Consumer();
            Task.Run(() => consumer.Consume());
        }

        /// <summary>
        /// Initializes the events to run methods when triggered.
        /// </summary>
        private void InitEventListeners()
        {
            UpdateGui.UpdateStockEvent += this.UpdateStockPredictions;
        }

        /// <summary>
        /// Updates the GUI to display predictions
        /// </summary>
        /// <param name="stockPrediction">the predictions</param>
        private void UpdateStockPredictions(string stockPrediction)
        {
            if (this.richTextBoxPredictions.InvokeRequired)
            {
                this.richTextBoxPredictions.Invoke((MethodInvoker)delegate
                    {
                        this.richTextBoxPredictions.Text = stockPrediction;
                    });
            }
            else
            {
                this.richTextBoxPredictions.Text = stockPrediction;
            }
        }

        /// <summary>
        /// Hooks onto buttonPredict click event
        /// </summary>
        /// <param name="sender">The context</param>
        /// <param name="e">event arguments</param>
        [SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:ElementMustBeginWithUpperCaseLetter", Justification = "Auto-generated by IDE")]
        private void buttonPredict_Click(object sender, System.EventArgs e)
        {
            var controller = new MakePredictions(this.textBoxEnterTicker.Text, this.comboBoxInfoSource.Text);
            controller.GetPredictions();
        }
    }
}
